apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myblog
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: myblog
  rules:
  - host: api.staging.cluster-1.nomkhonwaan-project.nomkhonwaan.com
    http:
      paths:
      - backend:
          serviceName: myblog-server
          servicePort: 9090
      - path: /blog-service
        backend:
          serviceName: myblog-gateway
          servicePort: 3000
